### ISSUE TITLE
Encoder.as의 setEncode 함수명

### ISSUE THREAD

**Issue by stzhyegeun** [stzjimin/Jimin_03#5]
함수명이 뭔가 할당하는 동작을 하는 것 같은데 
실제 동작은 초기화 입니다. 
함수명을 초기화 함수로 바꾸는게 좋지 않을까요?

**Comment by stzjimin** [comment]
맞는 말씀이신 것 같습니다!! 저도 함수명을 지으면서 좀 아니라고 생각은 했는데...마땅히 떠오르는 단어가 없어 인코드를 하기위해 세팅해준다...라는 느낌으로 지었었는데 지금보니 함수명이 전혀 다른 의미를 가지고있네요..
