### ISSUE TITLE
DataLoader 객체 생성 관련된 질문.

### ISSUE THREAD

**Issue by stzjongmin** [stzjimin/Jimin_03#6]
Assignment_03::onClickInputSelectButton() 함수에서 

new DataLoader(_file.nativePath, completeDataLoad); 

DataLoader 객체를 생성만 해두고 대입은 해두지 않는 데.. 어떤 이유 인지 궁금합니다.
나중에 자원 해제도 못하지 않나요..??

**Comment by stzjimin** [comment]
DataLoader클래스에서 static변수인 _dataStack과 _libName만 필요하고 객체를 다른곳에서 쓸필요가 없겠다고 생각해서 따로 대입을 해주지 않았는데 말씀해주신 자원해제의 문제는 제가 전혀 생각을 못하고있었습니다...
